services:
  backend:
    build: .
    network_mode: host
    devices:
      - /dev/hailo0:/dev/hailo0
    volumes:
      - ./baro.db:/app/baro.db
      - ./recordings:/app/recordings
    environment:
      - BACKEND_HOST=0.0.0.0
      - BACKEND_PORT=8080
      - YOLO_MODEL_PATH=models/yolo11n-pose_hailo_model
      - CORS_ORIGINS=http://localhost:5173,http://127.0.0.1:5173,http://192.168.0.8:5173
    restart: unless-stopped

  mediamtx:
    image: bluenviron/mediamtx:latest
    network_mode: host
    volumes:
      - ./mediamtx.yml:/mediamtx.yml
    restart: unless-stopped
